#!/usr/bin/env python3

import time
import json
import logging
import configparser
from datetime import datetime

logging.basicConfig(level=logging.DEBUG)

logging.info("Pool pH and temperature meter.")

from atlas import AtlasPH_I2C
from temperature import Temperature
from mqtt import MQTT

try:
    config_ini = sys.argv[1]
except:
    config_ini = "config.ini"

if __name__ == "__main__":
    config = configparser.ConfigParser()
    config.read(config_ini)

    mqtt = MQTT(config['mqtt'])
    temp_sensors = Temperature(config['temperature'])
    ph_sensor = AtlasPH_I2C(
        address = int(config['ph']['addr'], 0),
        bus = int(config['ph']['bus'], 0)
    )

    while True:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        result = {
            '_timestamp': timestamp
        }
        result['temperature'] = temp_sensors.read_all()
        result['ph'] = ph_sensor.read_ph()
        print(result, flush=True)
        mqtt.publish(config['mqtt']['topic'], json.dumps(result))
        time.sleep(60)
